spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.220.145:5432/db_sims?serverTimezone=GMT
    username: cai1010
    password: 342706aA

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mappers/*.xml





